services:
  proxy-cache:
    container_name: "proxy_cache"
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "redis_cache:/cache"
    command: ["redis-server"]
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 128M

volumes:
  redis_cache:
