#:schema https://json.schemastore.org/any.json
root = "."
tmp_dir = "tmp"

[build]
exclude = ["tmp", "vendor", "cmd"]

[color]
main = "yellow"
watcher = "cyan"
build = "green"
log = "white"

[screen]
clear_on_rebuild = true
