export type Segments =
  | "sponsor"
  | "selfpromo"
  | "intro"
  | "interaction"
  | "preview"
  | "poi_highlight"
  | "outro"
  | "filler"
  | "exclusive_access"
  | "music_offtopic"
  | "chapter"
