name: Repo housekeeping
on: [push, pull_request]

jobs:
  type-check:
    name: "Type check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install deps without lockfile
        run: pnpm install --no-lockfile

      - name: "Type check"
        run: pnpm lint

  knip-checks:
    name: "Unused components and files"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install deps without lockfile
        run: pnpm install --no-lockfile

      - name: "Knip check"
        run: pnpm run knip
